sudo: false
language: node_js
node_js:
  - "10.15.1"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test:db:start
  - yarn test:coverage
  - yarn test:db:stop