version: '3.1'

services:
  main-database:
    image: mariadb:10.4.5 
    container_name: ${DB_HOST}
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
