version: '3.1'

services:
  shop-db:
    image: mariadb:10.4.5 
    container_name: shop-db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
      MYSQL_DATABASE: main
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
  
  api-server:
    build: .
    container_name: api-server
    restart: on-failure
    ports:
      - 4000:4000
    depends_on:
      - shop-db